apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcsim
spec:
  selector:
    matchLabels:
      app: vcsim
  template:
    metadata:
      labels:
        app: vcsim
    spec:
      containers:
        - name: vcsim
          image: vmware/vcsim:latest
          ports:
            - name: https
              containerPort: 8989
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vcsim
spec:
  selector:
    app: vcsim
  ports:
    - name: https
      port: 443
      targetPort: 8989
