apiVersion: v2
name: event-router
description: The VMware Event Router is used to connect to various VMware event providers and forwards received events to supported event processors.
home: https://vmweventbroker.io/
type: application
version: v0.7.6
appVersion: v0.7.5
maintainers:
  - name: Michael Gasch
    email: mgasch@vmware.com
