---
builds:
  - id: router
    goos: &goos-defs
      - linux
      - darwin
      - windows
    goarch: &goarch-defs
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./cmd/router
    binary: router
    ldflags:
      - "-X main.version={{.Version}} -X main.commit={{.ShortCommit}}"

archives:
  - id: router
    builds:
      - router
    name_template: "router_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: vmware-samples
    name: vcenter-event-broker-appliance
  target_commitish: "{{ .Commit }}"
  name_template: "router_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
