---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-py-vm-attr-service
  labels:
    app: veba-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-py-vm-attr:1.3
        envFrom:
        - secretRef:
            name: vcconfig-secret
---
# Here is a list of triggers with event type filtering to match multiple kind of VM events
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-py-vm-attr-trigger-vmcreated
  labels:
    app: kn-py-vm-attr
spec:
  broker: default
  filter:
    attributes:
      type: com.vmware.vsphere.VmCreatedEvent.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-vm-attr-service
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-py-vm-attr-trigger-vmcloned
  labels:
    app: kn-py-vm-attr
spec:
  broker: default
  filter:
    attributes:
      type: com.vmware.vsphere.VmClonedEvent.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-vm-attr-service

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-py-vm-attr-trigger-vmregistered
  labels:
    app: kn-py-vm-attr
spec:
  broker: default
  filter:
    attributes:
      type: com.vmware.vsphere.VmRegisteredEvent.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-vm-attr-service

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-py-vm-attr-trigger-drsvmpoweredon
  labels:
    app: kn-py-vm-attr
spec:
  broker: default
  filter:
    attributes:
      type: com.vmware.vsphere.DrsVmPoweredOnEvent.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-vm-attr-service
