name: VMware Event Router Development Image Build

# triggered on every push to development but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  push:
    paths:
      - "vmware-event-router/**"
    branches:
      - "development"

# run all jobs with these defaults, unless specified otherwise
defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  image:
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20
    env:
      KO_DOCKER_REPO: us.gcr.io/daisy-284300/veba # .../router@sha256:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    
    steps:
      - name: Setup ko
        uses: imjasonh/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.6
        
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ matrix.go-version }}
        id: go
        
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - id: Login to GCP
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Get short COMMIT and TAG
        run: |
          echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
          echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV

      - name: Build and push multi-arch image
        run: |
          # build and push with development tag
          ko resolve --platform=linux/arm64,linux/amd64 --tags ${KO_COMMIT},development -BRf deploy/event-router-k8s.yaml