name: VMware Event Router Integration Tests

# triggered on every push and PRs but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'vmware-event-router/**'
  push:
    paths:
      - 'vmware-event-router/**'

# run all jobs with these defaults, unless specified otherwise
defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  integration-tests:
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20
    
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest 

      - name: Run OpenFaaS integration tests
        run: hack/run_integration_tests.sh
